name: Generate snake game

on:
  schedule:
    - cron: "0 */12 * * *" # every 12 hours on the hour
  workflow_dispatch:

jobs:
  build:
    name: Generate & Publish Snake
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Checkout the repository (needed for GitHub Pages action)
      - name: Checkout
        uses: actions/checkout@v4

      # Snake animation generator
      - name: Generate Snake SVG
        uses: Sutil/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake2.svg
          snake_color: 'blue'

      # Deploy SVG to `output` branch using GitHub Pages action
      - name: Publish to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
